const NAMESPACE = 'POSTS';

export const GET_POSTS = `${NAMESPACE}/GET_POSTS`;
export const GET_POSTS_REQUEST = `${NAMESPACE}/GET_POSTS_REQUEST`;
export const GET_POSTS_SUCCESS = `${NAMESPACE}/GET_POSTS_SUCCESS`;
export const GET_POSTS_FAILURE = `${NAMESPACE}/GET_POSTS_FAILURE`;
